app/controllers/web_git/commands_controller.rb

When students create the workspace for their assignment with Codio, there is no `.git` folder or history which will cause WebGit to silently fail. #25 
These changes will look for `.git` and if the folder doesn't exist, WebGit will initialize the repository and make an initial commit of all files.

Initialize git repo if there is no current .git folder

---

app/views/web_git/commands/status.html.erb

Fixes #33 
Since we're on Gitpod and can actually _use_ git remotes. Let's do it 😎 
Test with 
```ruby
gem 'web_git', github: 'firstdraft/web_git', branch: 'jw-undisable-buttons'
```
on Gitpod

Enable Buttons

---

app/controllers/web_git/commits_controller.rb
app/views/web_git/commands/status.html.erb
config/routes.rb

Fixes #38 
Previously, you could not push a branch to Github, since the button only triggered a `git push` and there would be no upstream for any new branches yet so the push would silently fail.
Now when users try to push any branch other than `master`, they do a `git push -u origin <branchname>`.
Add this branch to a project, `bundle`, and navigating to `/git` to check out the changes.
```ruby
gem 'web_git', github: 'firstdraft/web_git', branch: 'jw-set-upstream-for-new-branch'
```

Set upstream for any branch other than master

---

lib/views/status.erb

Fixes #53 
Add `required` attribute to all required inputs:
- commit title
- commit hash for checkout
- branch name for new branch

Add required attribute to commit input.

---

lib/web_git.rb

Resolves #52 
There appears to be a bug in the `status` method of the `ruby-git` gem that causes it to 
> be easily fooled by operations that don't change the content of a file such as deleting and
recreating it, or even running touch on a file.
ruby-git `status` [behind the scenes](https://github.com/ruby-git/ruby-git/blob/b8c63206f8d10f57892060375a86ae911fad356e/lib/git/status.rb#L160) calls `git diff-files` instead of actual `git status`. `git diff-files` shows[ all changes made to files](https://git-scm.com/docs/git-diff-files) (including mode and modification date changes), but only until `git diff` is called once.
The proposed change should update the index to make it be in sync with the actual contents of the working directory and thus make the `status` method work the same as the …

Make status consistent with CLI status.

---

lib/views/status.erb

Resolves #54
- Modifies branch name input `id` to be unique (there was a separate input with the same id) 
- Modifies jQuery to fill in `commit_hash` input when SHA is clicked
- Removes JS function to copy to clipboard
- Removes hidden SHA input that was used for copying to clipboard
Add gem to `Gemfil`e to test
```ruby
gem "web_git", github: "firstdraft/web_git", branch: "jw-make-commit-sha-clickable"
```

Automatically fill in "Branch off of" input when SHA is clicked

---

lib/generators/web_git/install_generator.rb

Use Thor `inject_into_file` which is reversible.
Previously, I wasn't aware of the `force: true` flag  that is required for multiple insertions (for some reason?) so this wasn't possible.
In Gemfile
```ruby
gem "web_git", github: "firstdraft/web_git", branch: "jw-make-reversible-better-installer"
```
In Terminal
```bash
bundle install
rake g web_git:install
rake d web_git:install
```
and `config.ru` should be back to what it was before.

Make the installer reversible

---

lib/views/status.erb
lib/web_git.rb

Resolves #70 
I originally mistook this for https://github.com/firstdraft/appdev/issues/283
When creating a branch off of a specific commit, it will actually fail b/c of 
This is because the `name` of the input somehow become inconsistent with the key being used for `params`.
```erb
<label for="branch_name_sha">Branch name</label>
<input type="text" class="form-control" name="branch_name_sha"
id="branch_name_sha" placeholder="Enter a name for the new branch..."
required >
```
So
```ruby
name = params[:branch_name].downcase.gsub(" ", "_")
```
didn't work.
This branch changes the name to be consistent with the other checkout form, `branch_name`.
Test adding this to your Gemfile:
```
gem "web_git", github: "firstdraft/web_git", branch: "jw-fix-checking-out-branch"
```
```
bundle install
rake …
```

Make name of new branch inputs consistent.

---

lib/web_git.rb

Resolves #73 (hopefully) This issue [goes more in depth](https://github.com/firstdraft/web_git/issues/73#issuecomment-643471050)— here are the essentials:
This branch aims to change this code
```ruby
g.status.changed.each do
g.diff.entries
end
@changed_files = g.status.changed.keys
@deleted_files = g.status.added.keys
@untracked_files = g.status.untracked.keys
@added_files = g.status.deleted.keys
```
to this
```ruby
status = g.status
status.changed.each do
g.diff.entries
end
@changed_files = status.changed.keys
@deleted_files = status.added.keys
@untracked_files = status.untracked.keys
@added_files = status.deleted.keys
```
in an attempt to speed up the performance of the main status page.
According to `rack-mini-profilier`, the speed of rendering the page is currently **around 24~25 …

Reduce calls to git status

---

lib/web_git/graph.rb

It's possible that you can never stay on a separate branch. Currently the drawing of the graph doesn't take into account what branch you started on _before_ drawing the graph and the last branch name from` g.branches` will always be the branch you end up on.
The proposed changes fix that issue, by noting the current branch _before_ traversing the graph and checking it out before the page is rendered. 
The usual instructions
```ruby
gem "web_git", git: "https://github.com/firstdraft/web_git", branch: "jw-graph-should-end-on-starting-branch"
```
```bash
bundle install
rails g web_git:install
```

Graph should end on the branch you were on before creating the graph

---

lib/views/status.erb
lib/web_git.rb

Since we currently aren't doing any redirects with `notices` or `alerts`, it's a lot safe to not use the same Route to create a branch and also checkout one. This led to issues similar to https://github.com/firstdraft/web_git/pull/71 and introduced another bug of using `fetch` that prevents a User from checking out an existing branch.
The proposed changes fix the latter by separating `/branch/checkout` into 
- `/branch/checkout/new` for creating a branch
- `/branch/checkout` for switching to an existing branch
- Updates the form actions accordingly
- Updates the Controller Actions (what do you call them in Sinatra?) accordingly
The usual instructions
```ruby
gem "web_git", git: "https://github.com/firstdraft/web_git", branch: "jw-make-better-routes-for-branch-checkout"
```
```bash
bundle …
```

Separate Routes for creating a Branch and switching to an existing Branch

---

Gemfile.lock
lib/web_git.rb

Resolves #92 
It turns out students are unable to push other branches besides `master` to GitHub. This is because with `ruby-git` you have to specify which branch to push,[ otherwise it will default to `"master"`](https://github.com/ruby-git/ruby-git/blob/98270b66b09a9474d6c0ad6d83f384fb4596428a/lib/git/base.rb#L364-L369). Currently, `web_git` does not specify which branch to push. Since the default is `"master"` this also means that repos with only a `"main"` branch are impossible to push to GitHub.
This commit updates `ruby-git` and ensures that `web_git` pushes the current branch that the user is on.
```rb
gem "web_git", git: "https://github.com/firstdraft/web_git", branch: "jw-update-ruby-git"
```

Push to any branch

---

lib/views/status.erb
lib/web_git.rb

Resolves #93 
For now this just displays the `origin` remote, which is most useful. The graph should show other remotes due to changes in #95 . In a separate PR, we can add functionality to choose which remote to push to or how to best display all remotes.

Display origin git remote

---

lib/views/status.erb
lib/web_git.rb

Resolves #78 
Resolves #88 
Students often see a big ol' error page if Git or Gitpod settings aren't exactly right
Students should never see an error page like this. `web_git` should fail gracefully and redirect with a flash message if something doesn't work.
This PR does the following:
- Enables `session` in Sinatra to display flash messages.
- Refactors controller logic to rescue `Git::GitExecuteError` exceptions
- Displays flash messages on redirect

Add notice and alerts

---

lib/views/status.erb
lib/web_git.rb

Currently Bootstrap tooltips do not work.
Additionally, I switch `let` to the more widely supported `var` in the very rare case that someone tries to use an older browser.

Enable tooltips

---

lib/views/status.erb
lib/web_git.rb
lib/web_git/graph.rb

> I was thinking as a stopgap until we figure out some sort of JS graphing library to display the git graph, should we go back to my old hack of displaying the output of git sla at the bottom of /git? I feel like the tree view (with all the branches unified) is essential
>
>The downside is that we'd have to install the command-line tools that the old web_git depended on
`git sla` being an alias of `git log --oneline --decorate --graph --all`
Until it becomes feasible to draw the graph with the `git` gem, capture the output of the graph from the command line and display it below the commit form.
1. Add gem to `Gemfile`
```rb
gem "web_git", git: "https://github.com/firstdraft/web_git", branch: "jw-basic-cli-graph"
```
2. Run install command
```bash
rails g web_git:install
```
3. Run `rails …

Replace branch log with basic CLI graph

---

Gemfile
Gemfile.lock
lib/web_git/graph.rb
web_git.gemspec

Resolves #102 
Showing the Git graph is less usefull without color.
Add [`ansispan` gem](https://github.com/jelaniwoods/ansispan) to apply CSS color and style to the captured ansi-colored git graph while preserving the clickable SHAs.
1. Add gem to `Gemfile`
```rb
gem "web_git", git: "https://github.com/firstdraft/web_git", branch: "102-jw-add-color-to-graph"
```
2. Run install command
```bash
rails g web_git:install
```
3. Run `rails s`
4. Visit `/git`

Add color to git graph

---

lib/web_git.rb

Resolves #108 
Due to changes in https://github.com/firstdraft/web_git/pull/105
When a project has 1 commit on the current branch `git show HEAD~1` was being called which throws an error since it requires a previous commit.
Don't call `git show HEAD~1` when the log has one commit.

Fix show last commit for projects with 1 commit

---

lib/generators/web_git/install_generator.rb

Resolves #110 
Currently when the installer is run multiple times, additional `end`s or other Ruby is injected into `config.ru` which causes app breaking errors.
Update the installer to know when `config.ru` has the required web git settings so the app doesn't break.

Allow installer to run multiple times

---

lib/views/index.html

Resolves #123 
With the current usage instructions, non-Rails projects don't have a homepage and so starting the server they see a "No route matches" page.
There should instead be a default homepage with a link to navigate to the /git route.
This PR _does not_ update the install generator for non-Rails projects. Follow to #57 for that
Modify the `config.ru` in the parent project to look like this:
```ruby
require 'bundler/setup'
require "web_git"
map '/' do
dir = Gem::Specification.find_by_name('web_git').gem_dir
path = dir + '/lib/views/index.html'
default_homepage = File.read(path)
app = proc do |env|
[200, { 'Content-Type' => 'text/html' }, [default_homepage]]
end
run app
end
map '/git' do
run WebGit::Server
end
```

Add default homepage for non-Rails apps

---

lib/views/status.erb
lib/web_git.rb
lib/web_git/config.rb

Resolves #141 
The output of `heroku whomai` is confusing to students sometimes. We also don't plan to use Heroku for the foreseeable future, so running it preemptively is unnecessary.
Add ability to turn on/off Heroku features in an initializer. The Heroku settings are **not enabled by default**. This disables the Heroku nav tab and doesn't call `heroku whoami`. 
In the installed project, create an initializer file (`web_git.rb`) and toggle the Heroku features like this:
```rb
WebGit.config do |config|
config.heroku_enabled = true # is set to false by default
end
```

Add config settings to control Heroku features
